spring:
  application:
    name: microserver-discovery-eureka
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true